---
name: Fast PR Checks

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 1

jobs:
  parallel-checks:
    name: Parallel Checks
    runs-on: ubuntu-latest
    timeout-minutes: 8
    strategy:
      matrix:
        check: [fmt, clippy, build, test]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        if: matrix.check == 'fmt'
        run: cargo fmt -- --check

      - name: Run clippy
        if: matrix.check == 'clippy'
        run: cargo clippy --all-targets --all-features -- -W clippy::all

      - name: Build
        if: matrix.check == 'build'
        run: cargo build --all-targets --all-features

      - name: Run tests
        if: matrix.check == 'test'
        run: cargo test --all-features
